#!/usr/bin/env php
<?php

$_ENV['HOME'] = getenv('HOME');
$_ENV['VAGRANT_DOTFILE_PATH'] = homestead_path().DIRECTORY_SEPARATOR.'.vagrant';

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

function homestead_path()
{
    if (isset($_SERVER['HOME'])) {
        return $_SERVER['HOME'].'/.homestead';
    } else {
        return $_SERVER['HOMEDRIVE'].$_SERVER['HOMEPATH'].DIRECTORY_SEPARATOR.'.homestead';
    }
}

$app = new Symfony\Component\Console\Application('Laravel Homestead', '2.2.2');

$app->add(new Attluh\Parstead\DestroyCommand);
$app->add(new Attluh\Parstead\EditCommand);
$app->add(new Attluh\Parstead\HaltCommand);
$app->add(new Attluh\Parstead\InitCommand);
$app->add(new Attluh\Parstead\MakeCommand);
$app->add(new Attluh\Parstead\ProvisionCommand);
$app->add(new Attluh\Parstead\ResumeCommand);
$app->add(new Attluh\Parstead\RunCommand);
$app->add(new Attluh\Parstead\UpCommand);
$app->add(new Attluh\Parstead\UpdateCommand);
$app->add(new Attluh\Parstead\SshCommand);
$app->add(new Attluh\Parstead\SshConfigCommand);
$app->add(new Attluh\Parstead\StatusCommand);
$app->add(new Attluh\Parstead\SuspendCommand);

$app->run();
